import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const app = await readFile(new URL("../app.js", import.meta.url), "utf8");
const boot = await readFile(new URL("../miniapp-boot.js", import.meta.url), "utf8");
const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const styles = await readFile(new URL("../styles.css", import.meta.url), "utf8");
const landing = await readFile(new URL("../landing.html", import.meta.url), "utf8");
const offer = await readFile(new URL("../offer.html", import.meta.url), "utf8");

assert.match(html, /role="status"[^>]*aria-live="polite"/);
assert.match(html, /viewport-fit=cover/);
assert.match(html, /styles\.css\?v=20260822-editorial-path-1/);
assert.match(boot, /config\.onerror = showFailure/);
assert.match(boot, /app\.onerror = showFailure/);
assert.match(boot, /today\.onerror = showFailure/);
assert.match(boot, /setTimeout\(showFailure, 15000\)/);
assert.match(boot, /assetVersion = "20260822-editorial-path-1"/);
assert.doesNotMatch(boot, /app\.src = ".\/app\.js\?v=" \+ configVersion/);

assert.match(app, /new AbortController\(\)/);
assert.match(app, /NETWORK_TIMEOUT_MS = 10000/);
assert.match(app, /\/api\/profile\?refresh=1/);
assert.match(app, /function normalizeProfile\(raw\)/);
assert.match(app, /function normalizeDeepSessions\(value\)/);
assert.match(app, /p\.deep_sessions = normalizeDeepSessions\(p\.deep_sessions\)/);
assert.match(app, /DEEP_SESSION_STATUSES/);
assert.match(app, /exactContract = Array\.isArray\(value\)/);
assert.match(app, /result\.user_words/);
assert.match(app, /takeaway: cleanText\(result\.takeaway\)/);
assert.match(app, /next_step: cleanText\(result\.next_step\)/);
assert.doesNotMatch(app, /raw_transcript|crisis_reason/);

assert.match(app, /role", "tablist"/);
assert.match(app, /role", "tabpanel"/);
assert.match(app, /ArrowLeft/);
assert.match(app, /BackButton/);
assert.match(app, /function pathPanel\(p\)/);
assert.match(app, /Твой цикл изменения/);
assert.match(app, /\/api\/outcomes/);
assert.match(app, /function outcomeQuestion\(/);
assert.match(app, /без текста и темы/);
assert.match(app, /Любой исход подходит/);
assert.match(app, /deep_helpfulness/);
assert.match(app, /deep_followup/);
assert.doesNotMatch(app, /outcome_feedback.*intention|outcome_feedback.*user_words/);
assert.match(app, /function deepSessionsPanel\(p\)/);
assert.match(app, /Дословно из твоих сообщений/);
assert.match(app, /Выдели 20–30 минут/);
assert.match(app, /не за рулём и не на работе/);
assert.doesNotMatch(app, /Твои подтверждённые слова/);
assert.match(app, /Гипотеза проводника, не факт/);
assert.match(app, /\/api\/deep-session\/delete/);
assert.match(app, /session_id: sessionId/);
assert.match(app, /Связанный с ним текущий шаг тоже будет удалён/);
assert.match(app, /Подтверждённый итог пока не сохранён/);
assert.match(app, /Скопировать \/imagine/);
assert.match(app, /Ты управляешь памятью/);
assert.match(app, /\/deleteall/);
assert.match(app, /\/export/);

assert.match(app, /payments_available === false/);
assert.match(app, /Новое оформление временно закрыто/);
assert.match(app, /Не покупай Stars специально для MindCoach/);
assert.match(app, /\[\["30 дней", monthly \+ " Stars"\]/);
assert.match(app, /\["365 дней", annual \+ " Stars · разово"\]\]/);
assert.match(app, /Number\(b\.monthly_xtr\) \|\| 500/);
assert.match(app, /Number\(b\.annual_xtr\) \|\| 5000/);
assert.match(app, /@PremiumBot/);
assert.match(app, /Пополни баланс минимум на/);
assert.match(app, /Проверь рублёвую цену/);
assert.doesNotMatch(app, /карта Мир|карты Мир|МИР/);
assert.match(app, /status === "failed"/);
assert.match(app, /status === "pending"/);
assert.match(app, /status === "cancelled"/);

assert.match(app, /themeChanged/);
assert.match(app, /themeParams/);
assert.match(app, /colorScheme/);
assert.match(app, /setBottomBarColor/);
assert.match(styles, /--tg-theme-bg-color/);
assert.match(styles, /--tg-content-safe-area-inset-bottom/);
assert.match(styles, /--tg-viewport-stable-height/);
assert.match(styles, /prefers-reduced-motion: reduce/);
assert.match(styles, /min-width: 320px/);
assert.match(styles, /min-height: 44px/);
assert.match(styles, /\.outcome-option[\s\S]*min-height: 48px/);
assert.match(styles, /\.outcome-options[\s\S]*gap: 8px/);

assert.match(app, /Сессия завершилась/);
assert.match(app, /Обновить статус/);
assert.match(app, /function changeExperimentView\(raw\)/);
assert.match(app, /Пауза тоже часть пути/);
assert.match(app, /labelText = "К чему вернуться"/);
assert.match(app, /ctaLabel = "Продолжить эту тему"/);
assert.doesNotMatch(app, /latestMemory\.summary \+ " Что изменилось/);
assert.match(app, /\/api\/memory\/forget/);
assert.match(app, /Забыть именно эту запись/);
assert.match(app, /не восстановится автоматически/);
assert.match(app, /через \/reset/);
assert.match(html, /id="action-status"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(app, /function psycheMap\(sections, archetypes\)/);
assert.doesNotMatch(app, /root\.appendChild\(pathBlock/);
assert.doesNotMatch(app, /root\.appendChild\(upgradeNudge/);

assert.match(landing, />500 <span>Stars \/ 30 дней<\/span>/);
assert.match(landing, /Годовой доступ: 5000 Stars/);
assert.match(landing, /Пополните баланс минимум на 500 Stars/);
assert.match(offer, /30 дней — 500 Telegram Stars/);
assert.match(offer, /365 дней — 5000 Telegram Stars/);
assert.match(offer, /@PremiumBot/);
assert.doesNotMatch(landing, /Подписка за 250 Telegram/);

console.log("Mini App redesign smoke passed");
